// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var
     runtime=globalThis.jsoo_runtime,
     global_data=runtime.caml_get_global_data(),
     Sexplib0_Sexp=global_data.Sexplib0__Sexp,
     Sexplib0_Sexp_conv=global_data.Sexplib0__Sexp_conv,
     t_of_sexp=Sexplib0_Sexp[1],
     sexp_of_t=Sexplib0_Sexp[2],
     equal=Sexplib0_Sexp[3],
     compare=Sexplib0_Sexp[4],
     Not_found_s=Sexplib0_Sexp[5],
     Of_sexp_error=Sexplib0_Sexp[6],
     message=Sexplib0_Sexp[7],
     default_indent=Sexplib0_Sexp[8],
     pp_hum=Sexplib0_Sexp[9],
     pp_hum_indent=Sexplib0_Sexp[10],
     pp_mach=Sexplib0_Sexp[11],
     pp=Sexplib0_Sexp[12],
     to_string_hum=Sexplib0_Sexp[13],
     to_string_mach=Sexplib0_Sexp[14],
     to_string=Sexplib0_Sexp[15],
     of_float_style=Sexplib0_Sexp[16],
     of_int_style=Sexplib0_Sexp[17],
     Private=Sexplib0_Sexp[18],
     t_sexp_grammar=Sexplib0_Sexp_conv[59],
     Sexp=
      [0,
       t_of_sexp,
       sexp_of_t,
       equal,
       compare,
       Not_found_s,
       Of_sexp_error,
       message,
       default_indent,
       pp_hum,
       pp_hum_indent,
       pp_mach,
       pp,
       to_string_hum,
       to_string_mach,
       to_string,
       of_float_style,
       of_int_style,
       Private,
       t_sexp_grammar],
     Ppx_sexp_conv_lib=[0,Sexp];
    runtime.caml_register_global(2,Ppx_sexp_conv_lib,"Ppx_sexp_conv_lib");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJwcHhfc2V4cF9jb252X2xpYi5jbWEuanMiLCJzb3VyY2VSb290IjoiIiwibmFtZXMiOlsidF9zZXhwX2dyYW1tYXIiXSwic291cmNlcyI6WyIvVXNlcnMvYXphdC8ub3BhbS80LjE0LjAvbGliL3BweF9zZXhwX2NvbnYvcnVudGltZS1saWIvcHB4X3NleHBfY29udl9saWIubWwiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7S0FPTUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztVIiwic291cmNlc0NvbnRlbnQiOlsibW9kdWxlIENvbnYgPSBTZXhwbGliMC5TZXhwX2NvbnZcbm1vZHVsZSBDb252X2Vycm9yID0gU2V4cGxpYjAuU2V4cF9jb252X2Vycm9yXG5tb2R1bGUgU2V4cF9ncmFtbWFyID0gU2V4cGxpYjAuU2V4cF9ncmFtbWFyXG5cbm1vZHVsZSBTZXhwID0gc3RydWN0XG4gIGluY2x1ZGUgU2V4cGxpYjAuU2V4cFxuXG4gIGxldCB0X3NleHBfZ3JhbW1hciA9IENvbnYuc2V4cF90X3NleHBfZ3JhbW1hclxuZW5kXG5cbm1vZHVsZSBTZXhwYWJsZSA9IFNleHBsaWIwLlNleHBhYmxlXG4iXX0=
