// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var runtime=globalThis.jsoo_runtime;
    function pre_test_hook(_a_){return 0}
    var Inline_test_config=[0,pre_test_hook];
    runtime.caml_register_global(0,Inline_test_config,"Inline_test_config");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJpbmxpbmVfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbInByZV90ZXN0X2hvb2siXSwic291cmNlcyI6WyIvVXNlcnMvYXphdC8ub3BhbS80LjE0LjAvbGliL3BweF9pbmxpbmVfdGVzdC9jb25maWcvaW5saW5lX3Rlc3RfY29uZmlnLm1sIl0sIm1hcHBpbmdzIjoiOzs7OztJO0lBSW9CLFNBQWhCQSxtQjtJQUFnQiwwQkFBaEJBO0lBQWdCO1UiLCJzb3VyY2VzQ29udGVudCI6WyJtb2R1bGUgdHlwZSBTID0gc2lnXG4gIHZhbCBwcmVfdGVzdF9ob29rIDogdW5pdCAtPiB1bml0XG5lbmRcblxubGV0IHByZV90ZXN0X2hvb2sgPSBpZ25vcmVcbiJdfQ==
