lib: [
  "_build/install/default/lib/OCanren-ppx/META"
  "_build/install/default/lib/OCanren-ppx/dune-package"
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.a" {"internals/myhelpers.a"}
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.cma" {"internals/myhelpers.cma"}
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.cmi" {"internals/myhelpers.cmi"}
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.cmt" {"internals/myhelpers.cmt"}
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.cmx" {"internals/myhelpers.cmx"}
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.cmxa" {"internals/myhelpers.cmxa"}
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.ml" {"internals/myhelpers.ml"}
  "_build/install/default/lib/OCanren-ppx/opam"
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/deriving_reify.ml" {"ppx_deriving_reify/deriving_reify.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.a" {"ppx_deriving_reify/ppx_deriving_reify.a"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.cma" {"ppx_deriving_reify/ppx_deriving_reify.cma"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.cmi" {"ppx_deriving_reify/ppx_deriving_reify.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.cmt" {"ppx_deriving_reify/ppx_deriving_reify.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.cmx" {"ppx_deriving_reify/ppx_deriving_reify.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.cmxa" {"ppx_deriving_reify/ppx_deriving_reify.cmxa"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.ml" {"ppx_deriving_reify/ppx_deriving_reify.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify__Deriving_reify.cmi" {"ppx_deriving_reify/ppx_deriving_reify__Deriving_reify.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify__Deriving_reify.cmt" {"ppx_deriving_reify/ppx_deriving_reify__Deriving_reify.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify__Deriving_reify.cmx" {"ppx_deriving_reify/ppx_deriving_reify__Deriving_reify.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.a" {"ppx_distrib/ppx_distrib.a"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cma" {"ppx_distrib/ppx_distrib.cma"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cmi" {"ppx_distrib/ppx_distrib.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cmt" {"ppx_distrib/ppx_distrib.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cmti" {"ppx_distrib/ppx_distrib.cmti"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cmx" {"ppx_distrib/ppx_distrib.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cmxa" {"ppx_distrib/ppx_distrib.cmxa"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.ml" {"ppx_distrib/ppx_distrib.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.mli" {"ppx_distrib/ppx_distrib.mli"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__.cmi" {"ppx_distrib/ppx_distrib__.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__.cmt" {"ppx_distrib/ppx_distrib__.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__.cmx" {"ppx_distrib/ppx_distrib__.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__.ml" {"ppx_distrib/ppx_distrib__.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__Ppx_distrib_expander.cmi" {"ppx_distrib/ppx_distrib__Ppx_distrib_expander.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__Ppx_distrib_expander.cmt" {"ppx_distrib/ppx_distrib__Ppx_distrib_expander.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib__Ppx_distrib_expander.cmx" {"ppx_distrib/ppx_distrib__Ppx_distrib_expander.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib_expander.ml" {"ppx_distrib/ppx_distrib_expander.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.a" {"ppx_fresh/ppx_fresh.a"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.cma" {"ppx_fresh/ppx_fresh.cma"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.cmi" {"ppx_fresh/ppx_fresh.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.cmt" {"ppx_fresh/ppx_fresh.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.cmx" {"ppx_fresh/ppx_fresh.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.cmxa" {"ppx_fresh/ppx_fresh.cmxa"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.ml" {"ppx_fresh/ppx_fresh.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.a" {"ppx_repr/ppx_repr.a"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.cma" {"ppx_repr/ppx_repr.cma"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.cmi" {"ppx_repr/ppx_repr.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.cmt" {"ppx_repr/ppx_repr.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.cmx" {"ppx_repr/ppx_repr.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.cmxa" {"ppx_repr/ppx_repr.cmxa"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.ml" {"ppx_repr/ppx_repr.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.a" {"ppx_tester/ppx_tester.a"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.cma" {"ppx_tester/ppx_tester.cma"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.cmi" {"ppx_tester/ppx_tester.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.cmt" {"ppx_tester/ppx_tester.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.cmx" {"ppx_tester/ppx_tester.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.cmxa" {"ppx_tester/ppx_tester.cmxa"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.ml" {"ppx_tester/ppx_tester.ml"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.a" {"ppx_wildcard/ppx_wildcard.a"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.cma" {"ppx_wildcard/ppx_wildcard.cma"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.cmi" {"ppx_wildcard/ppx_wildcard.cmi"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.cmt" {"ppx_wildcard/ppx_wildcard.cmt"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.cmx" {"ppx_wildcard/ppx_wildcard.cmx"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.cmxa" {"ppx_wildcard/ppx_wildcard.cmxa"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.ml" {"ppx_wildcard/ppx_wildcard.ml"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.a" {"prepare_fully_abstract/prepare_fully_abstract.a"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cma" {"prepare_fully_abstract/prepare_fully_abstract.cma"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cmi" {"prepare_fully_abstract/prepare_fully_abstract.cmi"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cmt" {"prepare_fully_abstract/prepare_fully_abstract.cmt"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cmti" {"prepare_fully_abstract/prepare_fully_abstract.cmti"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cmx" {"prepare_fully_abstract/prepare_fully_abstract.cmx"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cmxa" {"prepare_fully_abstract/prepare_fully_abstract.cmxa"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.ml" {"prepare_fully_abstract/prepare_fully_abstract.ml"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.mli" {"prepare_fully_abstract/prepare_fully_abstract.mli"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.a" {"reify_impl/reify_impl.a"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.cma" {"reify_impl/reify_impl.cma"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.cmi" {"reify_impl/reify_impl.cmi"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.cmt" {"reify_impl/reify_impl.cmt"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.cmx" {"reify_impl/reify_impl.cmx"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.cmxa" {"reify_impl/reify_impl.cmxa"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.ml" {"reify_impl/reify_impl.ml"}
]
libexec: [
  "_build/install/default/lib/OCanren-ppx/internals/myhelpers.cmxs" {"internals/myhelpers.cmxs"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx.exe" {"ppx_deriving_reify/ppx.exe"}
  "_build/install/default/lib/OCanren-ppx/ppx_deriving_reify/ppx_deriving_reify.cmxs" {"ppx_deriving_reify/ppx_deriving_reify.cmxs"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx.exe" {"ppx_distrib/ppx.exe"}
  "_build/install/default/lib/OCanren-ppx/ppx_distrib/ppx_distrib.cmxs" {"ppx_distrib/ppx_distrib.cmxs"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx.exe" {"ppx_fresh/ppx.exe"}
  "_build/install/default/lib/OCanren-ppx/ppx_fresh/ppx_fresh.cmxs" {"ppx_fresh/ppx_fresh.cmxs"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx.exe" {"ppx_repr/ppx.exe"}
  "_build/install/default/lib/OCanren-ppx/ppx_repr/ppx_repr.cmxs" {"ppx_repr/ppx_repr.cmxs"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx.exe" {"ppx_tester/ppx.exe"}
  "_build/install/default/lib/OCanren-ppx/ppx_tester/ppx_tester.cmxs" {"ppx_tester/ppx_tester.cmxs"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx.exe" {"ppx_wildcard/ppx.exe"}
  "_build/install/default/lib/OCanren-ppx/ppx_wildcard/ppx_wildcard.cmxs" {"ppx_wildcard/ppx_wildcard.cmxs"}
  "_build/install/default/lib/OCanren-ppx/prepare_fully_abstract/prepare_fully_abstract.cmxs" {"prepare_fully_abstract/prepare_fully_abstract.cmxs"}
  "_build/install/default/lib/OCanren-ppx/reify_impl/reify_impl.cmxs" {"reify_impl/reify_impl.cmxs"}
]
bin: [
  "_build/install/default/bin/pp_deriving_reify"
  "_build/install/default/bin/pp_distrib"
  "_build/install/default/bin/pp_fresh"
  "_build/install/default/bin/pp_ocanren_all"
  "_build/install/default/bin/pp_repr"
]
doc: [
  "_build/install/default/doc/OCanren-ppx/CHANGES"
  "_build/install/default/doc/OCanren-ppx/LICENSE"
  "_build/install/default/doc/OCanren-ppx/README.md"
  "_build/install/default/doc/OCanren-ppx/odoc-pages/index.mld" {"odoc-pages/index.mld"}
]
