name: Build and test

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "*"

env:
  OPAMROOT: /home/user/.opam
  OPAMYES: true

jobs:
  build:

    container:
      image: kakadu18/ocaml:fp2022

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        ocaml-compiler:
          - 4.14.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add submodules
        run: git submodule  update --init

      - run: sudo apt-get install libipc-system-simple-perl libstring-shellquote-perl -y

      - name: Add OCanren dependensais
        run: |
          opam install OCanren --deps-only --yes --with-test
          opam install js_of_ocaml js_of_ocaml-ppx mtime.1.4.0 --yes 
          opam install bisect_ppx

      - name: Build and test
        run: |
          opam exec -- dune build --profile=release
          opam exec -- dune test --profile=release Schedule

      - name: Send coverage
        run: |
          opam exec -- make send_coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}